import { Jost, Lexend, Teko, Inter } from "next/font/google";
import Navbar from "@/components/Shared/Navbar";
import "./globals.css";
//  Import fonts from Google
const jost = Jost({
  subsets: ["latin"],
  variable: "--font-jost",
});

const lexend = Lexend({
  subsets: ["latin"],
  variable: "--font-lexend",
});

const teko = Teko({
  subsets: ["latin"],
  variable: "--font-teko",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export const metadata = {
  title: "Qrinux ",
  description: "Generated by Qrinux ",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${jost.variable} ${lexend.variable} ${teko.variable} ${inter.variable}`}
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
